id = "pastel-night-theme"
name = "Pastel Night Theme"
version = "0.5.0"
schema_version = 1
authors = ["leolorenzato"]
description = "🌃 Night vibes with pastel lights"
repository = "https://github.com/leolorenzato/zed-pastel-night-theme"