id = "pastel-night"
name = "pastel-night"
version = "0.2.0"
schema_version = 1
authors = [""]
description = "🌃 Night vibes with pastel lights"
repository = "https://github.com/leolorenzato/zed-pastel-night-theme"